INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (1, 'Actifs', null, null, 1, null);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (2, 'Actifs courants', null, null, 1, 1);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (3, 'Cash', 100000.00, '101', 1, 2);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (4, 'Accounts Receivable', 50000.00, '102', 1, 2);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (5, 'Inventory', 75000.00, '103', 1, 2);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (6, 'Actifs non courants', null, null, 2, 1);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (7, 'Property', 500000.00, '110', 2, 6);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (8, 'Equipment', 300000.00, '111', 2, 6);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (9, 'Passifs et Capitaux propres', null, null, 3, null);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (10, 'Passifs courants', null, null, 3, 9);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (11, 'Accounts Payable', 80000.00, '201', 3, 10);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (12, 'Short-term Debt', 100000.00, '202', 3, 10);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (13, 'Passifs non courants', null, null, 4, 9);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (14, 'Long-term Debt', 300000.00, '210', 4, 13);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (15, 'Capitaux propres', null, null, 5, 9);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (16, 'Share Capital', 200000.00, '301', 5, 15);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (17, 'Retained Earnings', 150000.00, '302', 5, 15);
INSERT INTO public.rubriques (id_rubrique, rubrique, montant, n_compte, id_type, id_rubrique_mere) VALUES (18, 'Cash 2', 12333.00, null, 1, 2);
